---
- name: Installing dependencies for Debian
  ansible.builtin.apt:
    name:
      - gcc
      - make
      - pkg-config

- name: Installing PHP Dependencies
  ansible.builtin.apt:
    name:
      - libxml2-dev
      - libgd-dev
      - autoconf
      - libsodium-dev
      - libonig-dev
      - libcurl4-openssl-dev
      - libsqlite3-dev
      - libzip-dev
