---
- name: Install PHP oniguruma-devel - Fedora & Amazon {{ ansible_distribution_version }}
  when: ansible_distribution in ["Fedora", "Amazon"]
  ansible.builtin.dnf:
    name:
      - python3-libdnf5
      - oniguruma-devel
      - libzip-devel
    update_cache: true
    state: latest

- name: Install PHP oniguruma-devel - OracleLinux {{ ansible_distribution_version }}
  when: ansible_distribution == "OracleLinux" and (ansible_distribution_major_version is version('9', '>='))
  ansible.builtin.dnf:
    name: 
      - oniguruma-devel
      - libzip-devel
    enablerepo: ol9_codeready_builder
    update_cache: true
    state: latest

#https://yum.oracle.com/repo/OracleLinux/OL9/developer/EPEL/x86_64/getPackage/libsodium-devel-1.0.18-8.el9.x86_64.rpm
- name: Install PHP libsodium-devel - OracleLinux {{ ansible_distribution_version }}
  when: ansible_distribution == "OracleLinux" and (ansible_distribution_major_version is version('9', '>='))
  ansible.builtin.dnf:
    name: '*'
    enablerepo: ol9_developer_EPEL
    update_cache: true
    state: latest

- name: Import epel GPG key
  when: ansible_distribution in ["AlmaLinux", "CentOS", "Rocky"] and (ansible_distribution_major_version is version('9', '>='))
  ansible.builtin.rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    state: present

- name: Add Everything repository for libsodium-devel
  when: ansible_distribution in ["AlmaLinux", "CentOS", "Rocky"] and (ansible_distribution_major_version is version('9', '>='))
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Install PHP oniguruma Dependencies - {{ ansible_distribution }} {{ ansible_distribution_version }}
  when: ansible_distribution in ["AlmaLinux", "CentOS", "Rocky"] and (ansible_distribution_major_version is version('9', '>='))
  ansible.builtin.dnf:
    name:
      - oniguruma-devel
      - libzip-devel
    enablerepo: crb
    update_cache: true
    state: latest

- name: Installing dependencies for Redhat
  ansible.builtin.dnf:
    name: [gcc-c++, make]
    update_cache: true
    state: latest

- name: Install PHP Dependencies - {{ ansible_distribution }} {{ ansible_distribution_version }}
  ansible.builtin.dnf:
    name:
      - libxml2-devel
      - sqlite-devel
      - libcurl-devel
      - gd-devel
      - libsodium-devel
    update_cache: true
    state: latest